### ISSUE TITLE
problems with names 

### ISSUE THREAD

**Issue by geoffroyO** [namtpham/casia2groundtruth#3]
While downloading the database I noticed that there were a lot of problems with naming. Indeed some masks don't have the same names as the fake images, for example for the image "Tp_D_CNN_M_N_ind00091_10647.jpg " I can't find the mask that goes with it

**Comment by Karol-G** [comment]
I noticed that too :(

**Comment by namtpham** [comment]
> While downloading the database I noticed that there were a lot of problems with naming. Indeed some masks don't have the same names as the fake images, for example for the image "Tp_D_CNN_M_N_ind00091_10647.jpg " I can't find the mask that goes with it

Sorry for late reply.
I think you are talking about image _Tp_D_CNN_M_N_ind00091_ind00091_10647.jpg_ (double ind00091). This image was mistakenly labelled by the dataset authors because it is a copy-move image (TP_S), not a spliced image (TP_D). Many other images also have the naming problem. Therefore, I renamed the files as commands given in the excel file. Please take a look. I don't want to rename the files before uploading because I want to keep the dataset as it was originally posted by the authors.

**Comment by Karol-G** [comment]
Hi,

I manually went through the images and filtered out the ones with different GT names. My dataset therefore is different from the excel renaming, but that is okay for now in my case. I currently have not much time, but I will probably come back in a month or two and check out the excel table again. Thanks for your work on this though!

Best
Karol

**Comment by namtpham** [comment]
Hi Karol,

I guess you downloaded the dataset from a different source.
I no longer work with this dataset but if you have any concern, you can open an issue or feel free to send me an email, I am always happy to help.

Good luck!

**Comment by StevenLu2004** [comment]
Hi,

I noticed an issue with the Excel rename file:

- row 25: `Tp_S_NNN_S_N_sec00085_sec00085_00816.tif` &rarr; `Tp_S_NNN_S_N_ani00085_ani00085_00816.tif`
- row 119: `Tp_D_NNN_S_N_sec00085_sec00085_00816.tif` &rarr; `Tp_S_NNN_S_N_sec00085_sec00085_00816.tif`

Row 25 depends on 119 being done beforehand, so when I executed the commands in the order in the Excel file, I got a file-not-found error. Rows 23 and 79 have the same problem, except they're in the right order.

**Comment by namtpham** [comment]
Thank you Steven for your comment. I modified the excel file and provide a download link for dataset with already corrected names.

**Comment by StevenLu2004** [comment]
Np ;)

I also noticed that there are duplicate images in the authentic image set—specifically [these](https://pastebin.com/BBdwR3cX)

**Comment by namtpham** [comment]
Thx @StevenLu2004
I noticed this but didn't handle it completely :) I will add this link to the description.
