### ISSUE TITLE
CASIA2.0

### ISSUE THREAD

**Issue by laichou** [namtpham/casia2groundtruth#6]
Hello!
I want the CASIA2.0 dataset, and I also found that there is a problem of tampering with the image and the mask is inconsistent in this dataset. Do you have any corrected CASIA2.0 dataset?Or do you have a summary table of error messages?Can you send me a copy?
Thank you very much!

**Comment by namtpham** [comment]
Sorry for the late reply. Could you please specify the inconsistent problem?
If you want to download the original dataset provided by the authors, I can send a link. However, it contains many more errors than the revised version I did (see the readme and excel file <-- the summary table you ask).

**Comment by laichou** [comment]
这个问题我解决了，我还想请问您能发一下Columbia数据集中mask图转换成二值图之后的图吗？。因为我感觉我转换的不太严谨。谢谢！


酋
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "namtpham/casia2groundtruth"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月15日(星期二) 下午4:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [namtpham/casia2groundtruth] CASIA2.0 (Issue #6)





 
Sorry for the late reply. Could you please specify the inconsistent problem?
 If you want to download the original dataset provided by the authors, I can send a link. However, it contains many more errors than the revised version I did (see the readme and excel file <-- the summary table you ask).

**Comment by namtpham** [comment]
Its great, so I will close this issue. I will take a look at Columbia dataset if I have time.

**Comment by laichou** [comment]
好的谢谢！希望您看后能把您转换后的mask发给我，谢谢！




酋
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "namtpham/casia2groundtruth"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月15日(星期二) 下午5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [namtpham/casia2groundtruth] CASIA2.0 (Issue #6)





 
Its great, so I will close this issue. I will take a look at Columbia dataset if I have time.
